language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

before_script:
  - python setup.py develop
  - export HEP_PROJECT_ROOT=$PWD
  - export PATH=$PWD/bin:$PATH
  - python -c 'import hepshell'


script:
  - nosetests -v
  
